bundler_args: --without development
gemfile:
  - Gemfile
  - Gemfile.rack-1.3.x
language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - jruby-19mode
  - jruby-20mode
  - jruby-21mode
  - jruby-head
  - rbx
matrix:
  allow_failures:
    - rvm: jruby-head
  fast_finish: true
